title: "SudoHR"
theme: minima

header_pages:
  - UserGuide.md
  - DeveloperGuide.md
  - AboutUs.md

markdown: kramdown

repository: "AY2223S2-CS2103T-T17-2/tp"
github_icon: "images/github-icon.png"

plugins:
  - jemoji


enable_features:
  admonitions: true
  autoglossary: true

defaults:
  - scope:
      path: "" # Site-wide default
    values:
      master_branch: "https://github.com/AY2223S1-CS2103T-W16-2/tp/tree/master"
      main_src: "src/main/java/seedu/foodrem"

plugins:
  - jemoji